<a href="https://colab.research.google.com/github/xerxes786/Deep-Learning/blob/main/word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [2]:
voc_size=10000

In [3]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[803, 275, 4968, 4364], [803, 275, 4968, 5883], [803, 7777, 4968, 4560], [7942, 2829, 7044, 8448, 1520], [7942, 2829, 7044, 8448, 2882], [3583, 803, 7809, 4968, 1216], [2777, 4560, 718, 8448]]


In [4]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [5]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  803  275 4968 4364]
 [   0    0    0    0  803  275 4968 5883]
 [   0    0    0    0  803 7777 4968 4560]
 [   0    0    0 7942 2829 7044 8448 1520]
 [   0    0    0 7942 2829 7044 8448 2882]
 [   0    0    0 3583  803 7809 4968 1216]
 [   0    0    0    0 2777 4560  718 8448]]


In [6]:
dim=10
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [8]:
print(model.predict(embedded_docs))

[[[ 0.0114693   0.00791685  0.00526707  0.02625329  0.04802034
    0.01209144  0.02839701 -0.04799514  0.04258246  0.04665042]
  [ 0.0114693   0.00791685  0.00526707  0.02625329  0.04802034
    0.01209144  0.02839701 -0.04799514  0.04258246  0.04665042]
  [ 0.0114693   0.00791685  0.00526707  0.02625329  0.04802034
    0.01209144  0.02839701 -0.04799514  0.04258246  0.04665042]
  [ 0.0114693   0.00791685  0.00526707  0.02625329  0.04802034
    0.01209144  0.02839701 -0.04799514  0.04258246  0.04665042]
  [-0.01948134 -0.03324334  0.01491436 -0.03539919 -0.02669729
    0.02699583  0.02574008 -0.0413716  -0.02662423 -0.03889437]
  [-0.00652491 -0.0459609  -0.01930226 -0.02448686  0.04701353
   -0.02808298 -0.02360543  0.03753331  0.00354251  0.04384187]
  [ 0.00635435  0.01093279  0.0392959  -0.02595035  0.00685722
    0.03606943 -0.04051023 -0.04551145  0.02119663  0.00825592]
  [ 0.00157429 -0.04676182  0.02920205  0.0431239  -0.02805388
   -0.00502936  0.04892257  0.01734337 -0.002470

In [9]:
embedded_docs[0]

array([   0,    0,    0,    0,  803,  275, 4968, 4364], dtype=int32)

In [10]:
print(model.predict(embedded_docs)[0])

[[ 0.0114693   0.00791685  0.00526707  0.02625329  0.04802034  0.01209144
   0.02839701 -0.04799514  0.04258246  0.04665042]
 [ 0.0114693   0.00791685  0.00526707  0.02625329  0.04802034  0.01209144
   0.02839701 -0.04799514  0.04258246  0.04665042]
 [ 0.0114693   0.00791685  0.00526707  0.02625329  0.04802034  0.01209144
   0.02839701 -0.04799514  0.04258246  0.04665042]
 [ 0.0114693   0.00791685  0.00526707  0.02625329  0.04802034  0.01209144
   0.02839701 -0.04799514  0.04258246  0.04665042]
 [-0.01948134 -0.03324334  0.01491436 -0.03539919 -0.02669729  0.02699583
   0.02574008 -0.0413716  -0.02662423 -0.03889437]
 [-0.00652491 -0.0459609  -0.01930226 -0.02448686  0.04701353 -0.02808298
  -0.02360543  0.03753331  0.00354251  0.04384187]
 [ 0.00635435  0.01093279  0.0392959  -0.02595035  0.00685722  0.03606943
  -0.04051023 -0.04551145  0.02119663  0.00825592]
 [ 0.00157429 -0.04676182  0.02920205  0.0431239  -0.02805388 -0.00502936
   0.04892257  0.01734337 -0.00247041  0.01683707]]